FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.14

USER root

WORKDIR /var/www/html

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:ondrej/php

ENV PHP_FPM \
    php8.1-fpm \
    php8.1-curl \
    php8.1-xsl \
    php8.1-intl \
    php8.1-mysql \
    php8.1-soap \
    php8.1-zip \
    php8.1-opcache \
    php8.1-bcmath \
    php8.1-gd \
    php8.1-mbstring \
    php8.1-xdebug

RUN apt-get update && apt-get install -y \
    $PHP_FPM \
    vim \
    unzip \
    zip \
    cron \
    nano \
    procps \
    ssmtp mailutils \
    default-mysql-client \
    nginx \
    wget \
    net-tools \
    --no-install-recommends

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Add bash
ADD bash/.vimrc /root/.vimrc
ADD bash/.bash_aliases /usr/local/share/.bash_aliases
ADD bash/start_elasticsearch /usr/local/bin/start_elasticsearch
RUN chmod 0777 /usr/local/bin/start_elasticsearch

# Config mysql
ADD mysql/create-db.sql /var/www/create-db.sql
RUN yes | apt-get install -y mysql-server-8.0 \
    && service mysql start \
    && sleep 5 \
    && mysql -u root -proot < /var/www/create-db.sql \
    && rm -rf /var/www/create-db.sql

# Config nginx
ADD nginx/host.conf /etc/nginx/host.conf
ADD nginx/magento.conf /etc/nginx/conf.d/default.conf
ADD nginx/nginx.conf /etc/nginx/nginx.conf

# Config php-fpm
ADD php-fpm/zz-docker.conf /etc/php/8.1/fpm/pool.d/www.conf
ADD php-fpm/99-xdebug.ini /usr/local/etc/php/conf.d/
ADD php-fpm/php-custom.ini $PHP_INI_DIR/conf.d/

# Terminal interface
RUN printf 'PS1="\[\e[32m\]\u\[\e[m\]\[\e[34m\]@\[\e[m\]\[\e[36m\]\w\[\e[m\] \[\e[35m\]\T\[\e[m\] ➞ "\n\
. /usr/local/share/.bash_aliases\n' | tee --append /etc/bash.bashrc /root/.bashrc
